//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace XexToolGUI.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("XexToolGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] About_sound {
            get {
                object obj = ResourceManager.GetObject("About_sound", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap AboutToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("AboutToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap AboutToolStripMenuItem1_Image {
            get {
                object obj = ResourceManager.GetObject("AboutToolStripMenuItem1.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap AP25ToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("AP25ToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BackupxexToolStripButton_Image {
            get {
                object obj = ResourceManager.GetObject("BackupxexToolStripButton.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BinaryToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("BinaryToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Clear2ToolStripButton_Image {
            get {
                object obj = ResourceManager.GetObject("Clear2ToolStripButton.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ClearToolStripMenuItem1_Image {
            get {
                object obj = ResourceManager.GetObject("ClearToolStripMenuItem1.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap CMDToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("CMDToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap CompressedToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("CompressedToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap DashToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("DashToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap DevkitToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("DevkitToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap DumbToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("DumbToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap EncryptedToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("EncryptedToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ExitToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("ExitToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ExitToolStripMenuItem2_Image {
            get {
                object obj = ResourceManager.GetObject("ExitToolStripMenuItem2.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap HelpToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("HelpToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap HelpToolStripMenuItem2_Image {
            get {
                object obj = ResourceManager.GetObject("HelpToolStripMenuItem2.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap HxDToolStripMenuItem1_Image {
            get {
                object obj = ResourceManager.GetObject("HxDToolStripMenuItem1.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap IdcFileForIDAToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("IdcFileForIDAToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap InfoToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("InfoToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap InfoToolStripMenuItem1_Image {
            get {
                object obj = ResourceManager.GetObject("InfoToolStripMenuItem1.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap InfoToolStripMenuItem2_Image {
            get {
                object obj = ResourceManager.GetObject("InfoToolStripMenuItem2.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap KeyvaultToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("KeyvaultToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap MediaToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("MediaToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap OpenxexButton_Image {
            get {
                object obj = ResourceManager.GetObject("OpenxexButton.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap OpenxexpButton_Image {
            get {
                object obj = ResourceManager.GetObject("OpenxexpButton.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap PatchxexToolStripButton_Image {
            get {
                object obj = ResourceManager.GetObject("PatchxexToolStripButton.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap PathnameToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("PathnameToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ReadInfoToolStripButton_Image {
            get {
                object obj = ResourceManager.GetObject("ReadInfoToolStripButton.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap RegionToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("RegionToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap RequiredToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("RequiredToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap RetailToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("RetailToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SaveButton_Image {
            get {
                object obj = ResourceManager.GetObject("SaveButton.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SavexexToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("SavexexToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SelectToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("SelectToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SelectxexToolStripMenuItem1_Image {
            get {
                object obj = ResourceManager.GetObject("SelectxexToolStripMenuItem1.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap TitleUpdatesToolStripMenuItem1_Image {
            get {
                object obj = ResourceManager.GetObject("TitleUpdatesToolStripMenuItem1.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ToolStripDropDownButton10_Image {
            get {
                object obj = ResourceManager.GetObject("ToolStripDropDownButton10.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ToolStripDropDownButton3_Image {
            get {
                object obj = ResourceManager.GetObject("ToolStripDropDownButton3.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ToolStripDropDownButton4_Image {
            get {
                object obj = ResourceManager.GetObject("ToolStripDropDownButton4.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ToolStripDropDownButton6_Image {
            get {
                object obj = ResourceManager.GetObject("ToolStripDropDownButton6.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ToolStripDropDownButton7_Image {
            get {
                object obj = ResourceManager.GetObject("ToolStripDropDownButton7.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ToolStripDropDownButton8_Image {
            get {
                object obj = ResourceManager.GetObject("ToolStripDropDownButton8.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ToolStripDropDownButton9_Image {
            get {
                object obj = ResourceManager.GetObject("ToolStripDropDownButton9.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap UncompressedToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("UncompressedToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap UncryptedToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("UncryptedToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap WxPirsToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("WxPirsToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap XexBasicToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("XexBasicToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap XexExtendedToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("XexExtendedToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xextool {
            get {
                object obj = ResourceManager.GetObject("xextool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap XMLToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("XMLToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ZeroIDToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("ZeroIDToolStripMenuItem.Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
